CREATE OR REPLACE FILE FORMAT ECOMMERCE_DB.RAW.CSV_FORMAT
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL', 'null')
    EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE STAGE ECOMMERCE_DB.RAW.OLIST_STAGE
    FILE_FORMAT = ECOMMERCE_DB.RAW.CSV_FORMAT;

    