version: 2

sources:
  - name: raw
    database: ECOMMERCE_DB
    schema: RAW

    tables:
      - name: CUSTOMERS
      - name: ORDERS
      - name: ORDER_ITEMS
      - name: ORDER_PAYMENTS
      - name: ORDER_REVIEWS
      - name: PRODUCTS
      - name: PRODUCT_CATEGORY_TRANSLATION
      - name: SELLERS